[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && cp serve.json dist/serve.json"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3